<?php

namespace Database\Seeders;

use App\Models\JobPost;
use App\Models\User;
use Illuminate\Database\Seeder;

class JobPostSeeder extends Seeder
{
    public function run(): void
    {
        $hr = User::firstOrCreate(
            ['email' => 'hr@cvactive.vn'],
            ['name' => 'HR Manager', 'password' => bcrypt('password'), 'role' => 'hr']
        );

        $jobs = [
            [
                'title' => 'Senior Laravel Developer',
                'company_name' => 'TechVN Solutions',
                'company_description' => 'Công ty công nghệ hàng đầu Việt Nam với hơn 10 năm kinh nghiệm trong lĩnh vực phát triển phần mềm.',
                'location' => 'Hà Nội',
                'job_type' => 'full-time',
                'experience_level' => 'senior',
                'category' => 'it',
                'salary_min' => 30000000,
                'salary_max' => 50000000,
                'is_remote' => true,
                'is_hot' => true,
                'description' => "Yêu cầu:\n- Tối thiểu 5 năm kinh nghiệm với Laravel\n- Thành thạo PHP 8.x, MySQL, Redis\n- Có kinh nghiệm với Docker, CI/CD\n- Kỹ năng làm việc nhóm tốt\n\nMô tả công việc:\n- Phát triển và bảo trì các ứng dụng web\n- Thiết kế và tối ưu hóa database\n- Viết API cho frontend và mobile app\n- Tham gia code review và mentoring",
                'contact_email' => 'recruit@techvn.vn',
                'status' => 'published',
                'published_at' => now()->subDays(2),
                'expires_at' => now()->addDays(25),
                'views_count' => 342,
            ],
            [
                'title' => 'Frontend Developer (Vue.js)',
                'company_name' => 'Digital Agency ABC',
                'company_description' => 'Agency sáng tạo chuyên về thiết kế web và app cho thị trường Việt Nam và quốc tế.',
                'location' => 'TP. Hồ Chí Minh',
                'job_type' => 'full-time',
                'experience_level' => 'middle',
                'category' => 'it',
                'salary_min' => 20000000,
                'salary_max' => 35000000,
                'is_remote' => true,
                'is_hot' => false,
                'description' => "- Tối thiểu 2 năm kinh nghiệm với Vue.js hoặc React\n- Thành thạo HTML5, CSS3, JavaScript ES6+\n- Có kinh nghiệm với TailwindCSS hoặc Bootstrap\n- Hiểu biết về UX/UI design là điểm cộng\n\nTrách nhiệm:\n- Xây dựng giao diện người dùng\n- Tối ưu hiệu suất ứng dụng web\n- Làm việc chặt chẽ với team design",
                'contact_email' => 'hr@abcagency.vn',
                'status' => 'published',
                'published_at' => now()->subDays(5),
                'expires_at' => now()->addDays(20),
                'views_count' => 189,
            ],
            [
                'title' => 'Marketing Manager',
                'company_name' => 'BrandUp Vietnam',
                'company_description' => 'Công ty chuyên về branding và marketing online cho doanh nghiệp vừa và nhỏ.',
                'location' => 'Hà Nội',
                'job_type' => 'full-time',
                'experience_level' => 'senior',
                'category' => 'marketing',
                'salary_min' => 25000000,
                'salary_max' => 40000000,
                'is_remote' => false,
                'is_hot' => true,
                'description' => "- Tối thiểu 5 năm kinh nghiệm trong lĩnh vực marketing\n- Thành thạo Digital Marketing (SEO, SEM, Social Media)\n- Kinh nghiệm quản lý đội ngũ từ 3 người trở lên\n- Bằng cấp Marketing hoặc related fields\n\nTrách nhiệm:\n- Xây dựng chiến lược marketing tổng thể\n- Quản lý ngân sách marketing\n- Đo lường và báo cáo hiệu quả chiến dịch",
                'contact_email' => 'tuyendung@brandup.vn',
                'status' => 'published',
                'published_at' => now()->subDay(),
                'expires_at' => now()->addDays(30),
                'views_count' => 521,
            ],
            [
                'title' => 'UI/UX Designer',
                'company_name' => 'Creative Studio VN',
                'company_description' => 'Studio thiết kế sáng tạo chuyên về UI/UX, graphic design và motion graphics.',
                'location' => 'TP. Hồ Chí Minh',
                'job_type' => 'full-time',
                'experience_level' => 'middle',
                'category' => 'design',
                'salary_min' => 15000000,
                'salary_max' => 30000000,
                'is_remote' => true,
                'is_hot' => false,
                'description' => "- Tối thiểu 2 năm kinh nghiệm UI/UX\n- Thành thạo Figma, Adobe XD\n- Portfolio ấn tượng\n- Hiểu biết về design system\n\nTrách nhiệm:\n- Thiết kế giao diện cho web và mobile app\n- Nghiên cứu user và tạo wireframe\n- Làm việc với developers để implement design",
                'contact_email' => 'design@creativestudio.vn',
                'status' => 'published',
                'published_at' => now()->subDays(3),
                'expires_at' => now()->addDays(15),
                'views_count' => 276,
            ],
            [
                'title' => 'Kế toán tổng hợp',
                'company_name' => 'Tập đoàn Tài Chính ABC',
                'company_description' => 'Tập đoàn tài chính lớn tại Việt Nam với hoạt động đa ngành.',
                'location' => 'Hà Nội',
                'job_type' => 'full-time',
                'experience_level' => 'middle',
                'category' => 'finance',
                'salary_min' => 15000000,
                'salary_max' => 25000000,
                'is_remote' => false,
                'is_hot' => false,
                'description' => "- Tối thiểu 3 năm kinh nghiệm kế toán\n- Tốt nghiệp Đại học Kinh tế, Tài chính\n- Thành thạo phần mềm kế toán (MISA, Fast)\n- Có chứng chỉ CPA là điểm cộng\n\nTrách nhiệm:\n- Thực hiện hạch toán kế toán\n- Lập báo cáo tài chính\n- Quyết toán thuế hàng quý/năm",
                'contact_email' => 'hr@abcgroup.vn',
                'status' => 'published',
                'published_at' => now()->subDays(7),
                'expires_at' => now()->addDays(18),
                'views_count' => 98,
            ],
            [
                'title' => 'Nhân viên Telesale',
                'company_name' => 'Smart Sales Co.',
                'company_description' => 'Công ty chuyên cung cấp giải pháp bán hàng và chăm sóc khách hàng.',
                'location' => 'Hà Nội',
                'job_type' => 'full-time',
                'experience_level' => 'fresher',
                'category' => 'sales',
                'salary_min' => 8000000,
                'salary_max' => 15000000,
                'is_remote' => false,
                'is_hot' => false,
                'description' => "- Tốt nghiệp THPT trở lên\n- Giọng nói dễ nghe, giao tiếp tốt\n- Có kinh nghiệm telesale là điểm cộng\n\nTrách nhiệm:\n- Gọi điện tư vấn sản phẩm\n- Chăm sóc và follow up khách hàng\n- Cập nhật thông tin khách hàng vào hệ thống",
                'contact_email' => 'recruit@smartsales.vn',
                'status' => 'published',
                'published_at' => now()->subDays(1),
                'expires_at' => now()->addDays(10),
                'views_count' => 445,
            ],
            [
                'title' => 'HR Specialist',
                'company_name' => 'People First Corp',
                'company_description' => 'Công ty tư vấn nhân sự hàng đầu với dịch vụ recruitment và HR consulting.',
                'location' => 'TP. Hồ Chí Minh',
                'job_type' => 'full-time',
                'experience_level' => 'junior',
                'category' => 'hr',
                'salary_min' => 12000000,
                'salary_max' => 20000000,
                'is_remote' => false,
                'is_hot' => false,
                'description' => "- Tối thiểu 1 năm kinh nghiệm HR\n- Tốt nghiệp Đại học chuyên ngành liên quan\n- Thành thạo MS Office, HR software\n- Kỹ năng giao tiếp tốt\n\nTrách nhiệm:\n- Tuyển dụng và onboard nhân sự\n- Quản lý hồ sơ nhân viên\n- Hỗ trợ training và phát triển",
                'contact_email' => 'careers@peoplefirst.vn',
                'status' => 'published',
                'published_at' => now()->subDays(4),
                'expires_at' => now()->addDays(22),
                'views_count' => 134,
            ],
            [
                'title' => 'Thực tập sinh Backend',
                'company_name' => 'StartupHub VN',
                'company_description' => 'Startup công nghệ non trẻ với sản phẩm SaaS cho thị trường Đông Nam Á.',
                'location' => 'Hà Nội',
                'job_type' => 'internship',
                'experience_level' => 'fresher',
                'category' => 'it',
                'salary_min' => 5000000,
                'salary_max' => 8000000,
                'is_remote' => true,
                'is_hot' => false,
                'description' => "- Sinh viên năm 3-4 hoặc mới tốt nghiệp ngành CNTT\n- Biết PHP/Laravel hoặc Python/Django\n- Có kiến thức cơ bản về database\n\nTrách nhiệm:\n- Hỗ trợ phát triển API\n- Viết unit test\n- Tham gia meetings và học hỏi từ senior devs",
                'contact_email' => 'intern@startuphub.vn',
                'status' => 'published',
                'published_at' => now()->subDays(2),
                'expires_at' => now()->addDays(45),
                'views_count' => 623,
            ],
            [
                'title' => 'DevOps Engineer',
                'company_name' => 'CloudScale Asia',
                'company_description' => 'Công ty chuyên về giải pháp cloud và infrastructure cho doanh nghiệp.',
                'location' => 'TP. Hồ Chí Minh',
                'job_type' => 'full-time',
                'experience_level' => 'senior',
                'category' => 'it',
                'salary_min' => 35000000,
                'salary_max' => 60000000,
                'is_remote' => true,
                'is_hot' => true,
                'description' => "- Tối thiểu 4 năm kinh nghiệm DevOps\n- Thành thạo AWS/GCP/Azure\n- Kinh nghiệm với Kubernetes, Docker\n- Biết Infrastructure as Code (Terraform)\n\nTrách nhiệm:\n- Xây dựng và quản lý CI/CD pipelines\n- Monitor và troubleshoot hệ thống\n- Tối ưu hóa infrastructure costs",
                'contact_email' => 'devops@cloudscale.asia',
                'status' => 'published',
                'published_at' => now()->subHours(12),
                'expires_at' => now()->addDays(30),
                'views_count' => 89,
            ],
            [
                'title' => 'Content Marketing Specialist',
                'company_name' => 'ContentLab Agency',
                'company_description' => 'Agency content marketing với đội ngũ writer chuyên nghiệp cho các thương hiệu lớn.',
                'location' => 'Hà Nội',
                'job_type' => 'full-time',
                'experience_level' => 'middle',
                'category' => 'marketing',
                'salary_min' => 10000000,
                'salary_max' => 18000000,
                'is_remote' => true,
                'is_hot' => false,
                'description' => "- Tối thiểu 2 năm kinh nghiệm content marketing\n- Kỹ năng viết lách tốt, portfolio ấn tượng\n- Hiểu biết về SEO content\n- Biết sử dụng các tool như Ahrefs, SEMrush\n\nTrách nhiệm:\n- Lên ý tưởng và viết nội dung\n- Quản lý lịch content\n- Phân tích hiệu quả nội dung",
                'contact_email' => 'join@contentlab.vn',
                'status' => 'published',
                'published_at' => now()->subDays(6),
                'expires_at' => now()->addDays(20),
                'views_count' => 203,
            ],
        ];

        foreach ($jobs as $j) {
            JobPost::updateOrCreate(
                ['title' => $j['title'], 'company_name' => $j['company_name']],
                array_merge($j, ['user_id' => $hr->id])
            );
        }
    }
}
